services:
  mongodb:
    image: mongo:latest
    container_name: movete_mongo_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: default
      MONGO_INITDB_ROOT_PASSWORD: fvHiNH8fD0N2xcKc

volumes:
  mongo_data:
